// MinecraftManager/frontend/src/components/Advancements.jsx
import React, { useEffect, useState } from "react";
import { api } from "../services/api";
import { Search, CheckCircle, Lock, Trophy } from "lucide-react";

export default function Advancements() {
  const [players, setPlayers] = useState([]);
  const [selectedPlayer, setSelectedPlayer] = useState(null);
  const [advancements, setAdvancements] = useState([]);
  const [rootAdvancements, setRootAdvancements] = useState([]);
  const [activeTab, setActiveTab] = useState(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    api.getPlayers().then((data) => {
      setPlayers(data);
      if (data.length > 0) setSelectedPlayer(data[0].uuid);
    });
  }, []);

  useEffect(() => {
    if (!selectedPlayer) return;
    setLoading(true);
    api.getAdvancements(selectedPlayer).then((data) => {
      const advs = data.advancements || [];
      setAdvancements(advs);

      const roots = advs.filter((a) => !a.parent);
      setRootAdvancements(roots);
      if (roots.length > 0) setActiveTab(roots[0].key);

      setLoading(false);
    });
  }, [selectedPlayer]);

  const getChildren = (parentId) => {
    return advancements.filter((a) => a.parent === parentId);
  };

  const AdvancementNode = ({ adv, depth = 0 }) => {
    const children = getChildren(adv.key);
    const isCompleted = adv.done;

    return (
      <div className="flex flex-col relative">
        <div className="flex items-center gap-4 p-4 rounded bg-[#E5E7EB] shadow-sm border border-gray-300">
           {/* Icon */}
           <div className={`w-12 h-12 flex items-center justify-center shrink-0 border-2 ${
               isCompleted ? 'bg-[#31AF7C] border-[#31AF7C] text-white' : 'bg-gray-400 border-gray-500 text-gray-700'
           }`}>
               {isCompleted ? <CheckCircle size={24} /> : <Lock size={24} />}
           </div>

           {/* Content */}
           <div className="flex-1 min-w-0">
              <h4 className="font-bold text-black truncate">
                  {adv.display.title}
              </h4>
              <p className="text-sm text-gray-600 truncate">{adv.display.description}</p>
           </div>

           {/* Badge for Frame Type */}
           {adv.display.frame === 'challenge' && (
               <div className="px-2 py-1 bg-[#D946EF] text-white text-[10px] font-bold uppercase rounded flex items-center gap-1">
                   <Trophy size={10} /> Challenge
               </div>
           )}
        </div>

        {/* Connector Line */}
        {children.length > 0 && (
            <div className="ml-6 pl-6 border-l-2 border-gray-400 py-4 space-y-4">
                {children.map(child => (
                    <AdvancementNode key={child.key} adv={child} depth={depth + 1} />
                ))}
            </div>
        )}
      </div>
    );
  };

  return (
    <div className="h-full flex flex-col p-8">
      <div className="flex justify-between items-center mb-8">
        <h2 className="text-4xl font-serif text-white">Logros</h2>
        
        <div className="relative">
            <select
              className="bg-[#E5E7EB] text-black px-4 py-2 rounded outline-none focus:ring-2 focus:ring-[#D946EF]"
              value={selectedPlayer || ""}
              onChange={(e) => setSelectedPlayer(e.target.value)}
            >
              <option value="" disabled>Seleccionar Jugador</option>
              {players.map((p) => (
                <option key={p.uuid} value={p.uuid}>
                  {p.name}
                </option>
              ))}
            </select>
        </div>
      </div>

      {loading ? (
        <div className="text-center mt-20 text-gray-400">Cargando logros...</div>
      ) : (
        <div className="flex-1 bg-[#1B193B] flex flex-col min-h-0 overflow-hidden"> {/* Added min-h-0 and overflow-hidden */}
          {/* Tabs */}
          <div className="flex overflow-x-auto bg-[#4B5563] p-0 shrink-0"> {/* Added shrink-0 */}
            {rootAdvancements.map((root) => (
              <button
                key={root.key}
                onClick={() => setActiveTab(root.key)}
                className={`px-6 py-3 text-sm font-bold transition-colors whitespace-nowrap ${
                  activeTab === root.key
                    ? "bg-[#D946EF] text-white" // Pink Active
                    : "text-gray-300 hover:bg-gray-600 hover:text-white"
                }`}
              >
                {root.display.title}
              </button>
            ))}
          </div>

          {/* Content Area */}
          <div className="flex-1 overflow-y-auto p-8 bg-[#D1D5DB]">
            {activeTab && advancements.find((a) => a.key === activeTab) ? (
                 <div className="max-w-4xl mx-auto pb-10">
                    <AdvancementNode
                        adv={advancements.find((a) => a.key === activeTab)}
                    />
                 </div>
              ) : (
                  <div className="text-center text-gray-600 mt-20">Selecciona una categoría</div>
              )}
          </div>
        </div>
      )}
    </div>
  );
}

// MinecraftManager/frontend/src/app/components/advancements/advancements.component.ts
import { Component, OnInit, OnDestroy, ElementRef, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';
import { TextureService } from '../../services/texture.service';
import { Player } from '../../models/player.model';
import { Advancement, NodePosition } from '../../models/advancement.model';
import { Subscription } from 'rxjs';

interface ConnectorLine {
  x1: number; y1: number;
  x2: number; y2: number;
}

@Component({
  selector: 'app-advancements',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './advancements.component.html',
  styleUrls: ['./advancements.component.css']
})
export class AdvancementsComponent implements OnInit, OnDestroy {
  players: Player[] = [];
  selectedPlayer: string | null = null;
  advancements: Advancement[] = [];
  rootAdvancements: Advancement[] = [];
  activeTab: string | null = null;
  loading = false;

  nodePositions: NodePosition[] = [];
  connectorLines: ConnectorLine[] = [];

  // Canvas pan state
  canvasOffsetX = 40;
  canvasOffsetY = 40;
  isDragging = false;
  dragStartX = 0;
  dragStartY = 0;
  startOffsetX = 0;
  startOffsetY = 0;

  // Tooltip
  hoveredNode: Advancement | null = null;
  tooltipPos = { x: 0, y: 0 };

  // Layout constants
  readonly NODE_SIZE = 52;
  readonly H_SPACING = 90;
  readonly V_SPACING = 68;

  private sub = new Subscription();

  constructor(
    private apiService: ApiService,
    public textureService: TextureService
  ) {}

  ngOnInit(): void {
    this.apiService.getPlayers().subscribe(data => {
      this.players = data;
      if (data.length > 0) {
        this.selectedPlayer = data[0].uuid;
        this.loadAdvancements();
      }
    });
  }

  onPlayerChange(): void {
    this.loadAdvancements();
  }

  selectTab(rootKey: string): void {
    this.activeTab = rootKey;
    this.buildTree();
  }

  private loadAdvancements(): void {
    if (!this.selectedPlayer) return;
    this.loading = true;
    this.apiService.getAdvancements(this.selectedPlayer).subscribe(data => {
      this.advancements = data.advancements || [];
      this.rootAdvancements = this.advancements.filter(a => !a.parent);
      if (this.rootAdvancements.length > 0 && !this.activeTab) {
        this.activeTab = this.rootAdvancements[0].key;
      }
      this.buildTree();
      this.loading = false;
    });
  }

  private buildTree(): void {
    if (!this.activeTab) return;

    const root = this.advancements.find(a => a.key === this.activeTab);
    if (!root) return;

    this.nodePositions = [];
    this.connectorLines = [];

    const rootNode = this.buildNodeTree(root);
    if (rootNode) {
      this.layoutTree(rootNode, 0, 0);
      this.flattenTree(rootNode);
      this.buildConnectors(rootNode);
    }
  }

  private buildNodeTree(adv: Advancement): NodePosition {
    const children = this.advancements
      .filter(a => a.parent === adv.key)
      .map(child => this.buildNodeTree(child));

    return {
      advancement: adv,
      x: 0,
      y: 0,
      children
    };
  }

  private layoutTree(node: NodePosition, depth: number, yOffset: number): number {

    node.x = depth * this.H_SPACING;

    if (node.children.length === 0) {
      node.y = yOffset;
      return 1; 
    }

    let totalRows = 0;
    for (const child of node.children) {
      const childRows = this.layoutTree(child, depth + 1, yOffset + totalRows * this.V_SPACING);
      totalRows += childRows;
    }

    const firstChildY = node.children[0].y;
    const lastChildY = node.children[node.children.length - 1].y;
    node.y = (firstChildY + lastChildY) / 2;

    return totalRows;
  }

  private flattenTree(node: NodePosition): void {
    this.nodePositions.push(node);
    for (const child of node.children) {
      this.flattenTree(child);
    }
  }

  private buildConnectors(node: NodePosition): void {
    const centerX = node.x + this.NODE_SIZE / 2;
    const centerY = node.y + this.NODE_SIZE / 2;

    for (const child of node.children) {
      const childCenterX = child.x + this.NODE_SIZE / 2;
      const childCenterY = child.y + this.NODE_SIZE / 2;

      const midX = (centerX + childCenterX) / 2;
      this.connectorLines.push({ x1: centerX, y1: centerY, x2: midX, y2: centerY });
      this.connectorLines.push({ x1: midX, y1: centerY, x2: midX, y2: childCenterY });
      this.connectorLines.push({ x1: midX, y1: childCenterY, x2: childCenterX, y2: childCenterY });

      this.buildConnectors(child);
    }
  }

  startDrag(event: MouseEvent): void {
    this.isDragging = true;
    this.dragStartX = event.clientX;
    this.dragStartY = event.clientY;
    this.startOffsetX = this.canvasOffsetX;
    this.startOffsetY = this.canvasOffsetY;
  }

  onDrag(event: MouseEvent): void {
    if (!this.isDragging) return;
    this.canvasOffsetX = this.startOffsetX + (event.clientX - this.dragStartX);
    this.canvasOffsetY = this.startOffsetY + (event.clientY - this.dragStartY);
  }

  endDrag(): void {
    this.isDragging = false;
  }

  showTooltip(event: MouseEvent, adv: Advancement): void {
    const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
    this.hoveredNode = adv;
    this.tooltipPos = { x: rect.left + rect.width / 2, y: rect.top };
  }

  hideTooltip(): void {
    this.hoveredNode = null;
  }

  getFrameClass(frame: string): string {
    const f = frame?.toLowerCase() || 'task';
    if (f === 'goal') return 'frame-goal';
    if (f === 'challenge') return 'frame-challenge';
    return 'frame-task';
  }

  get activeTabTitle(): string {
    const adv = this.advancements.find(a => a.key === this.activeTab);
    return adv?.display?.title || '';
  }


  get canvasWidth(): number {
    if (this.nodePositions.length === 0) return 800;
    return Math.max(...this.nodePositions.map(n => n.x)) + this.NODE_SIZE + 100;
  }

  get canvasHeight(): number {
    if (this.nodePositions.length === 0) return 600;
    return Math.max(...this.nodePositions.map(n => n.y)) + this.NODE_SIZE + 100;
  }

  ngOnDestroy(): void {
    this.sub.unsubscribe();
  }
}

<div class="h-full flex flex-col">
  <!-- Header with player selector -->
  <div class="flex justify-between items-center px-8 pt-6 pb-4">
    <h2 class="text-4xl font-serif text-white">Logros</h2>
    <select class="bg-[#E5E7EB] text-black px-4 py-2 rounded outline-none focus:ring-2 focus:ring-[#D946EF]"
            [(ngModel)]="selectedPlayer"
            (ngModelChange)="onPlayerChange()">
      <option [ngValue]="null" disabled>Seleccionar Jugador</option>
      @for (p of players; track p.uuid) {
        <option [ngValue]="p.uuid">{{ p.name }}</option>
      }
    </select>
  </div>

  @if (loading) {
    <div class="text-center mt-20 text-gray-400">Cargando logros...</div>
  } @else {
    <div class="flex-1 flex flex-col mx-8 mb-8 overflow-hidden">

      <div class="tab-bar">
        @for (root of rootAdvancements; track root.key) {
          <button class="tab-item"
                  [class.active]="activeTab === root.key"
                  (click)="selectTab(root.key)"
                  [title]="root.display.title">
            <img [src]="textureService.getTextureUrl(root.display.icon)"
                 [alt]="root.display.title"
                 class="pixelated tab-icon" />
          </button>
        }
      </div>

      <div class="advancement-canvas"
           (mousedown)="startDrag($event)"
           (mousemove)="onDrag($event)"
           (mouseup)="endDrag()"
           (mouseleave)="endDrag()">

        <div class="canvas-title">
          @if (activeTab) {
            {{ activeTabTitle }}
          }
        </div>

        <div class="canvas-inner"
             [style.transform]="'translate(' + canvasOffsetX + 'px, ' + canvasOffsetY + 'px)'"
             [style.width.px]="canvasWidth"
             [style.height.px]="canvasHeight">

          <svg class="connectors"
               [attr.width]="canvasWidth"
               [attr.height]="canvasHeight">
            @for (line of connectorLines; track $index) {
              <line [attr.x1]="line.x1"
                    [attr.y1]="line.y1"
                    [attr.x2]="line.x2"
                    [attr.y2]="line.y2" />
            }
          </svg>

          @for (node of nodePositions; track node.advancement.key) {
            <div class="advancement-node"
                 [class.completed]="node.advancement.done"
                 [ngClass]="getFrameClass(node.advancement.display.frame)"
                 [style.left.px]="node.x"
                 [style.top.px]="node.y"
                 (mouseenter)="showTooltip($event, node.advancement)"
                 (mouseleave)="hideTooltip()">
              <img [src]="textureService.getTextureUrl(node.advancement.display.icon)"
                   [alt]="node.advancement.display.title"
                   class="pixelated node-icon" />
            </div>
          }
        </div>
      </div>
    </div>
  }

  @if (hoveredNode) {
    <div class="mc-tooltip"
         [style.left.px]="tooltipPos.x"
         [style.top.px]="tooltipPos.y">
      <p class="tooltip-title" [class.completed]="hoveredNode.done" [class.challenge]="hoveredNode.display.frame.toLowerCase() === 'challenge'">
        {{ hoveredNode.display.title }}
      </p>
      <p class="tooltip-desc">{{ hoveredNode.display.description }}</p>
      <p class="tooltip-status" [class.done]="hoveredNode.done">
        {{ hoveredNode.done ? '✓ Completado' : '✗ Pendiente' }}
      </p>
    </div>
  }
</div>
